# Tiny Editor Configuration

[editor]
# Default font size
font_size = 14.0
# Theme: "dark" or "light"
theme = "dark"

[plugins]
# Default plugin directory
plugin_dir = "plugins"
# Enabled plugins - text-editor will load first, then its dependencies
enabled = ["cursor", "selection"]

# Text editor plugin configuration
#[plugins.text-editor]
#lib = "crates/plugins/text-editor/target/debug/libtext_editor_plugin.dylib"
#config = "crates/plugins/text-editor/plugin.toml"
# Watch lib and swap it in if it changes
#auto_reload = true

# Cursor plugin configuration
[plugins.cursor]
lib = "crates/plugins/cursor/target/debug/libcursor_plugin.dylib"
config = "crates/plugins/cursor/plugin.toml"
# Watch lib and swap it in if it changes
auto_reload = true

# Selection plugin configuration
[plugins.selection]
lib = "crates/plugins/selection/target/debug/libselection_plugin.dylib"
config = "crates/plugins/selection/plugin.toml"
# Watch lib and swap it in if it changes
auto_reload = true

[development]
# Enable debug output
debug = true
# Show frame times
show_fps = false
