[package]
name = "tiny-font"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-sdk = { path = "../sdk" }
parking_lot = "0.12"
ahash = "0.8"
swash = "0.1"
zeno = "0.2"
unicode-bidi = "0.3"
anyhow = "1.0"