[build]
rustflags = ["-Z", "threads=8"]
# codegen-backend = "cranelift"  # Disabled for now to use default LLVM

#[build]
#rustflags = ["-C", "target-cpu=native"]
#
#[profile.release]
#opt-level = 3
#lto = "fat"
#codegen-units = 1